export const USER_AGGREGATE_FACTORY = 'USER_AGGREGATE_FACTORY';
export const USER_MONGO_WRITE_REPOSITORY = 'USER_MONGO_WRITE_REPOSITORY';
export const USER_SERVICE = 'USER_SERVICE';

export enum UserCodes {
  CREATED = 'USER.CREATED',
  DETAILS = 'USER.DETAILS',
}

export enum UserErrorCodes {
  NOT_FOUND = 'USER.NOT_FOUND',
  DUPLICATE_KEY = 'USER.DUPLICATE_KEY',
}
