#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Compiling your project before committing👷‍♂️🏗️'

pnpm tsc

echo '🏗️👷 Testing your project before committing👷‍♂️🏗️'

pnpm run test -o

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

npx lint-staged

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'